spring:
  application:
    name: tmplt
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=template
    username: postgres
    password: 123
    hikari:
      schema: template
  liquibase:
    enabled: true
    change-log: classpath:/changelog.yml
    default-schema: template
    liquibase-schema: template
  cloud:
    config:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: "none"
    show-sql: true
    properties:
      hibernate:
        default_schema: template
  security:
    user:
      name: user
      password: password

  logging:
    level:
      root: info

tmplt:
  kafka:
    topic:
      update-transaction-status: "update-transaction-status"

