${pojo.getPackageDeclaration()}
// Generated by Hibernate Tools ${version}

<#assign classbody>
    <#include "PojoTypeDeclarationWithBuilder.ftl"/> {

    <#if !pojo.isInterface()>
        <#include "PojoFields.ftl"/>

        <#include "PojoPropertyAccessors.ftl"/>

        <#include "PojoToString.ftl"/>

        <#include "PojoEqualsHashcode.ftl"/>

    <#else>
        <#include "PojoInterfacePropertyAccessors.ftl"/>

    </#if>
    <#include "PojoExtraClassCode.ftl"/>

  }
</#assign>

${pojo.generateImports()}
import java.util.UUID;
import jakarta.persistence.*;
import lombok.Builder;
import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;
import lombok.Data;

${classbody}

